# Supabase Configuration for Tournament Management System

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://rotomtracks.es"
additional_redirect_urls = [
  "http://localhost:3000",
  "https://rotomtracks.es",
  "https://www.rotomtracks.es",
  "https://rotomtracks.cat",
  "https://www.rotomtracks.cat",
  "https://rotomtracks-with-supabase.vercel.app",
  "https://rotomtracks-with-supabase.vercel.app/auth/reset-password",
  "https://rotomtracks-with-supabase.vercel.app/auth/confirm"
]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[edge_runtime]
enabled = true

[analytics]
enabled = false